# Generated by Django 5.1.7 on 2025-03-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_participants_event_rsvps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='rsvps',
            new_name='participants',
        ),
    ]
