# Generated by Django 5.1.7 on 2025-03-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_rsvps_event_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participants',
            new_name='rsvps',
        ),
    ]
